#!/usr/bin/env python3
import os
import sys
from pathlib import Path
args = sys.argv[1:]
if args and args[0] == 'function':
    args = args[1:]
os.execv(str(Path(__file__).with_name('decomp')), ['decomp', 'match', *args])
